spring.application.name=foreman-backend

##DB config
#spring.datasource.url=jdbc:mysql://localhost:3306/foreman_backend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=9433
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.open-in-view=false
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#default server port 8080
#server.port=9090
jwt.secret=SECRETKEY262132262188BIGASSCREATEDINJULY252020
jwt.expiration=86400000

app.frontend-domain=http://localhost:5173


#RailwayDB Config
spring.datasource.url=jdbc:mysql://interchange.proxy.rlwy.net:14897/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=dWUncPyqumxWnpdMrWvYWaYGahwKYhQg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update